global using SqlSugar;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Controllers;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Authorization;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics;
global using System.Runtime.InteropServices;
global using System.Security.Claims;
global using System.Text;
global using UAParser;
global using Yitter.IdGenerator;
global using Vben.Common.Core;
global using Vben.Common.Core.Utils;
global using Vben.Common.Core.Attribute;
global using Vben.Common.Core.Config;
global using Vben.Common.Core.Filter;
global using Vben.Common.Sqlsugar.Config;
global using Vben.Common.Sqlsugar.Mvc.Pojo;
global using Vben.Common.Sqlsugar.Mvc.Dao;
global using Vben.Common.Sqlsugar.Mvc.Entity;
global using Vben.Common.Sqlsugar.Mvc.Api;
global using Vben.Common.Sqlsugar.Mvc.Service;
global using Newtonsoft.Json;


// global using Furion;
// global using Furion.DependencyInjection;
// global using Furion.EventBus;
// global using Furion.FriendlyException;
// global using Furion.JsonSerialization;
